2022-09-21 11:54:12,652 ERROR: Exception on /user/susan [GET] [in /home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/zozo/PycharmProjects/microblog/app/routes.py", line 81, in user
    return render_template("user.html", user=user, posts=posts.items,
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/zozo/PycharmProjects/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/zozo/PycharmProjects/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/zozo/PycharmProjects/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/zozo/PycharmProjects/microblog/app/templates/user.html", line 24, in block 'app_content'
    {{ form.hidden_tag() }}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-09-21 11:54:20,763 ERROR: Exception on /user/pasha [GET] [in /home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/zozo/PycharmProjects/microblog/app/routes.py", line 81, in user
    return render_template("user.html", user=user, posts=posts.items,
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/zozo/PycharmProjects/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/zozo/PycharmProjects/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/zozo/PycharmProjects/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/zozo/PycharmProjects/microblog/app/templates/user.html", line 24, in block 'app_content'
    {{ form.hidden_tag() }}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-09-21 11:54:25,950 ERROR: Exception on /user/susan [GET] [in /home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/zozo/PycharmProjects/microblog/app/routes.py", line 81, in user
    return render_template("user.html", user=user, posts=posts.items,
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/zozo/PycharmProjects/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/zozo/PycharmProjects/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/zozo/PycharmProjects/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/zozo/PycharmProjects/microblog/app/templates/user.html", line 24, in block 'app_content'
    {{ form.hidden_tag() }}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-09-21 11:58:18,473 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:50]
