2022-09-20 11:31:54,673 ERROR: Exception on /reset_password_request [POST] [in /home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/zozo/PycharmProjects/microblog/app/routes.py", line 154, in reset_password_request
    send_password_reset_email(user)
  File "/home/zozo/PycharmProjects/microblog/app/email.py", line 18, in send_password_reset_email
    text_body=render_template('email/reset_pasword.txt', user=user, token=token),
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_pasword.txt
2022-09-20 11:34:18,832 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 11:38:51,052 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 11:43:38,257 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 11:46:26,370 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 11:46:53,972 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 11:54:43,390 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 11:54:58,189 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 14:28:15,648 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:48]
2022-09-20 14:30:53,207 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:48]
2022-09-20 19:39:09,143 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:48]
2022-09-20 19:39:44,001 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:48]
2022-09-20 19:40:01,613 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:48]
2022-09-20 19:40:42,186 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:48]
2022-09-20 19:40:51,514 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:48]
2022-09-20 19:41:21,334 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:48]
2022-09-21 11:51:46,437 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:50]
2022-09-21 11:52:43,612 ERROR: Exception on /user/susan [GET] [in /home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/zozo/PycharmProjects/microblog/app/routes.py", line 81, in user
    return render_template("user.html", user=user, posts=posts.items,
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/zozo/PycharmProjects/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/zozo/PycharmProjects/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/zozo/PycharmProjects/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/zozo/PycharmProjects/microblog/app/templates/user.html", line 24, in block 'app_content'
    {{ form.hidden_tag() }}
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
